name: hippo
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pillow
  - nibabel
  - seaborn
  - curl
  - unzip
  - git
